/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}'],
  darkMode: 'class',
  theme: {
    extend: {
      borderRadius: {
        none: '0',
        sm: '0',
        DEFAULT: '0',
        md: '0',
        lg: '0',
        xl: '0',
        '2xl': '0',
        '3xl': '0',
        full: '0',
      },
      colors: {
        surface: {
          50: 'rgb(var(--surface-50) / <alpha-value>)',
          100: 'rgb(var(--surface-100) / <alpha-value>)',
          200: 'rgb(var(--surface-200) / <alpha-value>)',
          300: 'rgb(var(--surface-300) / <alpha-value>)',
          400: 'rgb(var(--surface-400) / <alpha-value>)',
          500: 'rgb(var(--surface-500) / <alpha-value>)',
          600: 'rgb(var(--surface-600) / <alpha-value>)',
          700: 'rgb(var(--surface-700) / <alpha-value>)',
          800: 'rgb(var(--surface-800) / <alpha-value>)',
          900: 'rgb(var(--surface-900) / <alpha-value>)',
          950: 'rgb(var(--surface-950) / <alpha-value>)',
        },
        primary: {
          DEFAULT: '#00ffcc',
          50: '#e6fff9',
          100: '#b3fff0',
          200: '#80ffe6',
          300: '#4dffdd',
          400: '#1affd3',
          500: '#00ffcc',
          600: '#00cca3',
          700: '#00997a',
          800: '#006652',
          900: '#003329',
        },
        accent: {
          DEFAULT: '#ffb000',
          50: '#fff7e6',
          100: '#ffebb3',
          200: '#ffdf80',
          300: '#ffd34d',
          400: '#ffc11a',
          500: '#ffb000',
          600: '#cc8d00',
          700: '#996a00',
          800: '#664700',
          900: '#332300',
        },
        phosphor: {
          green: '#00ff41',
          cyan: '#00ffcc',
          amber: '#ffb000',
        },
      },
      fontFamily: {
        mono: ['"IBM Plex Mono"', '"JetBrains Mono"', '"Share Tech Mono"', 'monospace'],
        display: ['"Press Start 2P"', 'monospace'],
      },
      keyframes: {
        'cursor-blink': {
          '0%, 100%': { opacity: '1' },
          '50%': { opacity: '0' },
        },
        'scan-line': {
          '0%': { transform: 'translateY(-100%)' },
          '100%': { transform: 'translateY(100vh)' },
        },
        'glow-pulse': {
          '0%, 100%': { boxShadow: '0 0 5px rgba(0,255,204,0.3), inset 0 0 5px rgba(0,255,204,0.1)' },
          '50%': { boxShadow: '0 0 15px rgba(0,255,204,0.5), inset 0 0 10px rgba(0,255,204,0.2)' },
        },
        'text-flicker': {
          '0%, 100%': { opacity: '1' },
          '92%': { opacity: '1' },
          '93%': { opacity: '0.8' },
          '94%': { opacity: '1' },
          '96%': { opacity: '0.9' },
        },
        'power-on': {
          '0%': { opacity: '0', transform: 'scaleY(0.01) scaleX(0.5)', filter: 'brightness(10)' },
          '50%': { opacity: '0.8', filter: 'brightness(2)' },
          '100%': { opacity: '1', transform: 'scaleY(1) scaleX(1)', filter: 'brightness(1)' },
        },
        'border-flicker': {
          '0%, 100%': { borderColor: 'rgba(0,255,204,0.3)' },
          '50%': { borderColor: 'rgba(0,255,204,0.6)' },
        },
      },
      animation: {
        'cursor-blink': 'cursor-blink 1s step-end infinite',
        'scan-line': 'scan-line 8s linear infinite',
        'glow-pulse': 'glow-pulse 2s ease-in-out infinite',
        'text-flicker': 'text-flicker 3s linear infinite',
        'power-on': 'power-on 0.4s ease-out',
        'border-flicker': 'border-flicker 2s ease-in-out infinite',
      },
    },
  },
  plugins: [],
};
